name: flutter_smart_repository
description: "A flexible, offline-first, multi-platform data repository designed for Flutter applications."
version: 0.0.1
homepage: https://github.com/BiaoMoussa/flutter_smart_repository.git
repository: https://github.com/BiaoMoussa/flutter_smart_repository.git

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^7.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true